/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import { CacheableResponsePlugin } from "workbox-cacheable-response";
import { clientsClaim, RouteHandlerCallbackOptions } from "workbox-core";
import { ExpirationPlugin } from "workbox-expiration";
import {
    createHandlerBoundToURL,
    precacheAndRoute,
    type PrecacheEntry,
} from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import {
    CacheFirst,
    NetworkOnly,
    StaleWhileRevalidate,
} from "workbox-strategies";

// InjectManifest replaces self.__WB_MANIFEST at build time with the list of
// precached assets. Declaring it here keeps the reference typed; without the
// build-time replacement it is undefined and precacheAndRoute throws.
declare global {
    interface ServiceWorkerGlobalScope {
        __WB_MANIFEST: Array<PrecacheEntry | string>;
    }
}

declare const self: ServiceWorkerGlobalScope;

const MEDIA_ART_CACHE = "media-art-v1";

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp("/[^/?]+\\.[^/]+$");
registerRoute(
    // Return false to exempt requests from being fulfilled by index.html.
    ({ request, url }: { request: Request; url: URL }) => {
        // If this isn't a navigation, skip.
        if (request.mode !== "navigate") {
            return false;
        }

        // If this is a URL that starts with /_, skip.
        if (url.pathname.startsWith("/_")) {
            return false;
        }

        // If this looks like a URL for a resource, because it contains
        // a file extension, skip.
        if (url.pathname.match(fileExtensionRegexp)) {
            return false;
        }

        // Return true to signal that we want to use the handler.
        return true;
    },
    createHandlerBoundToURL("/index.html")
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
    // Add in any other file extensions or routing criteria as needed.
    ({ url }) =>
        url.origin === self.location.origin && url.pathname.endsWith(".png"),
    // Customize this strategy as needed, e.g., by changing to CacheFirst.
    new StaleWhileRevalidate({
        cacheName: "images",
        plugins: [
            // Ensure that once this runtime cache reaches a maximum size the
            // least-recently used images are removed.
            new ExpirationPlugin({ maxEntries: 50 }),
        ],
    })
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener("message", (event) => {
    if (event.data && event.data.type === "SKIP_WAITING") {
        self.skipWaiting();
    }

    // The nextup and schedule images sit behind an auth guard, so cached copies
    // must not outlive the session on a shared device. The client posts this on
    // logout.
    if (event.data && event.data.type === "CLEAR_MEDIA_ART_CACHE") {
        event.waitUntil(caches.delete(MEDIA_ART_CACHE));
    }
});

// Any other custom service worker logic can go here.

// Media artwork proxied by our own server. Caching it means covers and posters
// that have already been seen keep rendering while offline, and repeat visits
// don't re-download them.
//
// These two are content addressed: the jukebox passes the album name as `hash`
// and Jellyfin passes an image tag as `imageTagsPrimary`, so the URL changes
// whenever the artwork changes. Workbox includes the query string in the cache
// key by default, which makes a stale entry impossible here - hence CacheFirst.
const CONTENT_ADDRESSED_ART_PATHS = [
    "/api/jukebox/coverart/",
    "/api/nextup/thumbnail/",
];

const artPlugins = () => [
    // Only cache successes. A 404 (no artwork for this album) or a 401
    // (expired session) must not be stored, so the client keeps falling back
    // to its placeholder and retries once it is signed in again.
    new CacheableResponsePlugin({ statuses: [200] }),
    new ExpirationPlugin({
        maxEntries: 500,
        maxAgeSeconds: 30 * 24 * 60 * 60,
        purgeOnQuotaError: true,
    }),
];

registerRoute(
    ({ url, sameOrigin }) =>
        sameOrigin &&
        CONTENT_ADDRESSED_ART_PATHS.some((path) =>
            url.pathname.startsWith(path)
        ),
    new CacheFirst({
        cacheName: MEDIA_ART_CACHE,
        plugins: artPlugins(),
    }),
    "GET"
);

// Sonarr/Radarr posters are served from a stable URL with no cache buster, so
// they can change upstream without the URL changing. Revalidate in the
// background instead of pinning the first response forever.
registerRoute(
    ({ url, sameOrigin }) =>
        sameOrigin && url.pathname.startsWith("/api/schedule/thumbnail/"),
    new StaleWhileRevalidate({
        cacheName: MEDIA_ART_CACHE,
        plugins: artPlugins(),
    }),
    "GET"
);

// Return a fixed response when for "get current profile" when offline
const networkOnly = new NetworkOnly();
const profileCurrentHandler = async (params: RouteHandlerCallbackOptions) => {
    // https://developers.google.com/web/tools/workbox/guides/advanced-recipes#offline_page_only
    try {
        // Attempt a network request.
        return await networkOnly.handle(params);
    } catch (error) {
        // If it fails, return the fallback.
        const fallbackObject = { id: -2, name: "", displayName: "OFFLINE" };
        return new Response(JSON.stringify(fallbackObject));
    }
};

registerRoute(new RegExp("/api/profile/current"), profileCurrentHandler, "GET");
