version: "3.8"
services:
  # USAGE: see README.md
  homeremote:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./apps/server/.env
    ports:
      - "3333:3333"
    container_name: homeremote-stack
    volumes:
      - ./apps/server/auth.json:/usr/src/dist/apps/server/auth.json
      - /var/run/docker.sock:/var/run/docker.sock
      - /foo/:/songsfrom
    restart: unless-stopped