import { Logger } from "@nestjs/common";
import { NestFactory } from "@nestjs/core";
import { DocumentBuilder, SwaggerModule } from "@nestjs/swagger";
import cookieParser from "cookie-parser";
import session from "express-session";
import { AppModule } from "./app/app.module";
import { getAuthConfig } from "./auth/constants";
import { isOidcEnabled } from "./auth/oidc.config";

declare const module: {
    hot: {
        accept: () => void;
        dispose: (x: () => Promise<void>) => Promise<void>;
    };
};

async function bootstrap() {
    const app = await NestFactory.create(AppModule);
    const globalPrefix = ""; // This value was generated by nx with value 'api'
    app.setGlobalPrefix(globalPrefix);
    app.use(cookieParser());

    // OIDC needs a short-lived session to carry the OAuth state/nonce/PKCE
    // verifier between the redirect to Authentik and the callback.
    if (isOidcEnabled()) {
        app.use(
            session({
                secret: getAuthConfig().secret,
                resave: false,
                saveUninitialized: false,
                cookie: {
                    httpOnly: true,
                    maxAge: 10 * 60 * 1000, // 10 minutes
                },
            })
        );
    }
    const port = process.env.PORT || 3333;

    if (process.env.NODE_ENV === "development") {
        Logger.log(`Starting OpenApi UI on http://localhost:${port}/api`);
        const config = new DocumentBuilder()
            .setTitle("Cats example")
            .setDescription("The cats API description")
            .setVersion("1.0")
            .addTag("cats")
            .build();
        const document = SwaggerModule.createDocument(app, config);
        SwaggerModule.setup("api", app, document);
    }

    await app.listen(port);
    if (module.hot) {
        module.hot.accept();
        module.hot.dispose(() => app.close());
    }
    Logger.log(
        `🚀 Application is running on: http://localhost:${port}/${globalPrefix} in ${
            process.env.NODE_ENV ?? "production"
        } mode`
    );
}

bootstrap();
